FROM node:8-alpine

EXPOSE 8000

RUN mkdir -p /projects/internal
WORKDIR /projects/internal

COPY package.json package-lock.json* ./
RUN npm install && npm cache clean --force

COPY . /project/internal

CMD ["npm", "test"]
